[package]
name = "brchd"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
toml = "0.5"
serde = { version="1", features=["derive"] }
log = "0.4.8"
failure = "0.1.6"
env_logger = "0.7.1"
actix-rt = "1.0.0"
actix-web = "2.0.0"
actix-multipart = "0.2.0"
futures = "0.3.4"
reqwest = "0.10.2"
sodiumoxide = { version="0.2.5", features=["use-pkg-config"] }
chrono = "0.4.10"
rand = "0.7.3"
