name: Binaries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
        - name: brchd-x86_64-static
          path: target/x86_64-unknown-linux-musl/release/brchd
          run: cargo build --verbose --release --no-default-features --features=crypto,httpd,spider,rustls --target x86_64-unknown-linux-musl
        - name: brchd-x86_64-minimal
          path: target/release/brchd
          run: cargo build --verbose --release --no-default-features --features=native-tls

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install musl-tools

    - name: Install musl rustup target
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build
      run: ${{ matrix.build.run }}

    - name: Strip binary
      run: strip ${{ matrix.build.path }}

    - name: Archive executable
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.build.name }}
        path: ${{ matrix.build.path }}
