name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies (apt)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libsodium-dev
    - name: Install dependencies (brew)
      if: matrix.os == 'macos-latest'
      run: brew install pkg-config libsodium
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
